services:
  - type: web
    name: gym-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        value: main
      - key: VAULT_FOLDER
        value: gym
